spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: ${POOL_SIZE}
      data-source-properties:
        stringtype: unspecified
