network-id-upgrader:
  network-id-old: ${NETWORK_ID_OLD:}
  network-id-new: ${NETWORK_ID_NEW:}

spring:
  main:
    web-application-type: none

    jpa:
      open-in-view: false

      hibernate:
        ddl-auto: validate

      properties:
        hibernate:
          schema_update:
            unique_constraint_strategy: RECREATE_QUIETLY
          jdbc:
            lob:
              non_contextual_creation: true

